### ISSUE TITLE
跑程序的问题

### ISSUE THREAD

**Issue by ming71** [woshiwwwppp/ryolov3research-pytorch-master#4]
很佩服您的代码能力，这么麻烦的程序写的很随性漂亮。真的很厉害！！（膜拜大佬）
最近想跑一下程序检测斜框目标，有几个疑问想请教一下：  
1. **valid的一个bug**:
  https://github.com/woshiwwwppp/ryolov3research-pytorch-master/blob/83cb5c2b703e6941e41fde41ec1a157566a5b21e/yolo/utility.py#L404-L419  上面代码处out_box的维度是`(num_boxes,5)`，但是后面遍历batch内图像时`out_boxes = out_box[k]`只取出一个box；导致计算AP遍历时的下面这句报错：https://github.com/woshiwwwppp/ryolov3research-pytorch-master/blob/83cb5c2b703e6941e41fde41ec1a157566a5b21e/yolo/utility.py#L417 因为`out_boxes[i]`是取出上面那个box的第一个坐标信息的标量，无法传入`rbox_iou`计算iou。不知道是不是我哪里的理解有误...==  

2. **速度**
riou实现用的是shapely，没有cuda计算overlap，会不会检测的速度很慢？我自己写的斜框检测奇慢无比，请问大佬有用cuda试着加速嘛 

3. **test检测报错** 
注释掉eval的部分直接训练2000epoch，让程序过拟合一张图片，得到的权重用`test.py`进行检测，报错如下：
```
Traceback (most recent call last):
  File "test.py", line 40, in <module>
    classes,confidence = config.dataSet['confidence'],NMS = config.dataSet['NMS'],CUDA= True)
  File "/py/ryolo/yolo/utility.py", line 230, in convert_yolo_outputs
    cla_id = torch.argmax(res[:,6:],dim=1)
RuntimeError: cannot perform reduction function max on tensor with no elements because the operation does not have an identity
```
将conf阈值设置为0.002才能跳过这个错误，似乎是2k轮都没学到东西....  
然后在此基础上，继续检测得到这里的bug:
https://github.com/woshiwwwppp/ryolov3research-pytorch-master/blob/83cb5c2b703e6941e41fde41ec1a157566a5b21e/test.py#L44-L45  
报错是`IndexError: string index out of range`，因为我是单类目标检测label都是ship,`out_classes[0]='ship'`,进而`out_classes[0][i]`索引的有误了，请问这个是不是我的设置有问题导致的？  

4. **检测结果**
避开上述问题，在输出侧将label直接赋值为'sihp'，训练3000epoches，loss基本下降到0附近不变，但是检测的结果都丢了：（我的anchor设置就是按照gt的尺寸设的，理论上不怎么回归就能达到极小值，角度也按大佬的设置为0-pi）
![pic_screenshot_16 11 2019](https://user-images.githubusercontent.com/43720092/68988433-48dda280-0872-11ea-93aa-5f6029841f7a.png)

5. **模型可视化**
在`train.py`中用您提供的tensorboardX接口记录计算图模型时报错：
```Traceback (most recent call last):
  File "train.py", line 97, in <module>
    w.add_graph(yolo, (dummy_input,))
  File "/home/bit530/anaconda3/envs/torch1.1/lib/python3.7/site-packages/tensorboardX/writer.py", line 738, in add_graph
    self._get_file_writer().add_graph(graph(model, input_to_model, verbose, **kwargs))
  File "/home/bit530/anaconda3/envs/torch1.1/lib/python3.7/site-packages/tensorboardX/writer.py", line 138, in add_graph
    graph = graph_profile[0]
TypeError: 'GraphDef' object is not subscriptable
```

 上面五个问题希望能帮忙解答，因为想先用起来再慢慢看程序，所以有的地方还不是很明白，感谢解答～～

**Comment by ming71** [comment]
弄了三天改了很多地方，训练的效果还是有问题....哪怕买你的程序也行，我毕业得靠这个单阶段旋转的，挺急的，自己写的程序效果一直不好....有意向请联系我（走投无路==）

**Comment by woshiwwwppp** [comment]
我跑的时候没有遇到你说的第1,3,5个问题，可能是版本的改动导致出问题了，之前没有加cuda，后来加了。我有时间再仔细看一下
第二个问题，riou实现在训练的时候，计算iou匹配用的是shapely，在做nms的时候用了cuda，不影响前向时间，我测过640*640的图40ms左右，还是deformable convolution以及加了卷积层的加强版
至于检测结果，调整的参数有很多，首先anchor的设置，你要用你的数据聚类获得，还有多个层的布置要参考fpn。还有confidence，ignore threshold，nms等。所有参数都是根据我的数据集设置的，你需要重新设置

**Comment by ming71** [comment]
非常感谢！我在验证时，各处参数如聚类，anchor等我都尽可能简化，直接按照单样本的gt设置的，以便验证训练的可行性。
此外还有例如各处缩放ratio传入的都是一个浮点数，但是实际应该是一个batch中图像的ratios序列（每张图片缩放比不一样）等问题。
程序后面的改动，如果能推送更新到github上，不胜感谢！！😂大佬真的厉害，向您学习！

**Comment by woshiwwwppp** [comment]
你说的ratio问题，我的数据集在制作的时候图片大小都resize到了一个尺度，所以只有一个ratio
不过我这个代码虽能跑，但如果目标太复杂，检测效果不太好，如果追求精度的同时还要速度，建议用以mobile net为backbone的r2cnn，800*800输入也有20帧左右，效果也很不错。https://github.com/DetectionTeamUCAS/R2CNN_Faster-RCNN_Tensorflow

**Comment by ming71** [comment]
> 但如果目标太复杂，检测效果不太好

好的，多谢指点。因为要做单阶段的检测器，对yolo熟悉些，所以想在此基础改成任意方向检测的。
还有下面的focal loss传入conf信息的是不是有误？`X[...,4,:,:]`是angle信息：
https://github.com/woshiwwwppp/ryolov3research-pytorch-master/blob/83cb5c2b703e6941e41fde41ec1a157566a5b21e/yolo/base_model.py#L291-L296
我自己写的旋转框yolo的mAP只能在0.20以下，效果太差。您的程序简单直观而且很漂亮，改起来很方便，所以想拿这个作为baseline继续改动。
不知道这个程序是不是最新的版本，如果这个就是最新的我继续看看自己是啥问题😂

**Comment by woshiwwwppp** [comment]
focal loss写错了的原因是之前试了一下，效果不太好，需要大量调参才有用，所以就没有管这一部分了。这个基本上是最新的了，跑应该是能跑的，还有那个tensorboard的问题好像是加了deformable convolution后就出问题了，直接用普通卷积应该是可以可视化的😂

**Comment by ming71** [comment]
多谢你啦，这个是最新的话，确实是我的问题比较大，还是慢慢排坑吧😂非常感谢！

**Comment by ZOUYIyi** [comment]
@woshiwwwppp 
大神您好，我同样遇到上述的几个问题，尤其是 3，4两个问题，如果阈值为0.2,则由于检测不到物体代码会报错，如果阈值非常低，为0.002，则会检测出一系列的从小到大的旋转框，但是其中不包括目标框。

**Comment by woshiwwwppp** [comment]
这个代码直接用在另外一个数据集上要调整很多东西。如果不想看代码直接用的话，建议用这里面的代码https://github.com/DetectionTeamUCAS/R2CNN_Faster-RCNN_Tensorflow

**Comment by ming71** [comment]
> @woshiwwwppp
> 大神您好，我同样遇到上述的几个问题，尤其是 3，4两个问题，如果阈值为0.2,则由于检测不到物体代码会报错，如果阈值非常低，为0.002，则会检测出一系列的从小到大的旋转框，但是其中不包括目标框。

这个repo直接使用不很方便，有些地方有点小问题（如SE的位置等），但是写的很好，建议可以自己借鉴和改动。借鉴他的deformable conv和SE我试着自己改的旋转目标yolov3在ICDAR15目前有0.65的F1score基本能用。

**Comment by ZOUYIyi** [comment]
> @woshiwwwppp
> 大神您好，我同样遇到上述的几个问题，尤其是 3，4两个问题，如果阈值为0.2,则由于检测不到物体代码会报错，如果阈值非常低，为0.002，则会检测出一系列的从小到大的旋转框，但是其中不包括目标框。
> 
> 这个repo直接使用不很方便，有些地方有点小问题（如SE的位置等），但是写的很好，建议可以自己借鉴和改动。借鉴他的deformable conv和SE我试着自己改的旋转目标yolov3在ICDAR15目前有0.65的F1score基本能用。

哇，又一位大神，我试着改了数据集读入之类的问题，但是改不动网络的结构，训练不出结果的问题还是没解决，能参考一下您的代码吗，，，十分感谢！

**Comment by ming71** [comment]
> > @woshiwwwppp
> > 大神您好，我同样遇到上述的几个问题，尤其是 3，4两个问题，如果阈值为0.2,则由于检测不到物体代码会报错，如果阈值非常低，为0.002，则会检测出一系列的从小到大的旋转框，但是其中不包括目标框。
> > 这个repo直接使用不很方便，有些地方有点小问题（如SE的位置等），但是写的很好，建议可以自己借鉴和改动。借鉴他的deformable conv和SE我试着自己改的旋转目标yolov3在ICDAR15目前有0.65的F1score基本能用。
> 
> 哇，又一位大神，我试着改了数据集读入之类的问题，但是改不动网络的结构，训练不出结果的问题还是没解决，能参考一下您的代码吗，，，十分感谢！

还在调试中，没有完善，全部弄好再发布

**Comment by baltam** [comment]
dalao你好，我和ming71以及ZOUYIyi一样，遇到了ming71之前所述的问题。我的设置参数为：
图像尺寸：（640，640）
使用83张图片kmeans聚类结果：
[167,38]
[233,31]
[266,49]
[381,44]
confidence:0.4
ignore threshold:0.4
nms:0.3
1.对于第一个问题，在train.py中取i>3时，会在utility.py的502行代码
if rbox_iou(gt_boxes[j], out_boxes[i]) > matchIou and gt_classes[j] == out_classes[i]:
报错IndexError: invalid index to scalar variable.
当i>5时，会出现
RuntimeError: cannot perform reduction function argmax on a tensor with no elements because the operation does not have an identity
2.对于第三个问题，注释掉eval部分直接train2000个epoch，test的时候不知道为什么confidence要取得非常低才能检测出边界框，但是绘制出的编辑框几乎与要标注的对象没有关联
3.dalao之前说没使用cuda的时候没有遇到过问题1 3，想问一下dalao之前没使用cuda的版本会在GitHub上公开么

**Comment by woshiwwwppp** [comment]
那你anchor的角度设置以及特征图上的布置是对的吗，这个cuda版本我是直接覆盖了之前的版本，可能变不回去了。还有就是我最近比较忙，可能没有时间打理这个项目，如果你是要用在其它项目或者比赛上，建议用我上面给的链接，如果是自己学习的话可以自己单步调试找一下bug，对自己的代码能力和网络的理解都是有帮助的。这个网络其实就是参照drbox改的，和原来的yolo差别不大，就是多回归了一个角度以及anchor不一样，很简单

**Comment by baltam** [comment]
感谢dalao回复，dalao的代码写的很好，跑应该是能跑的，先慢慢消化程序把它吃透，总之谢谢dalao了～

**Comment by ZOUYIyi** [comment]
好的，了解了，我自己再看一下这个，谢谢回复。------------------ 原始邮件 ------------------
发件人: "woshiwwwppp"<notifications@github.com>
发送时间: 2019年12月31日(星期二) 晚上7:17
收件人: "woshiwwwppp/ryolov3research-pytorch-master"<ryolov3research-pytorch-master@noreply.github.com>;
抄送: "ZOUYIyi"<1519036154@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [woshiwwwppp/ryolov3research-pytorch-master] 跑程序的问题 (#4)



那你anchor的角度设置以及特征图上的布置是对的吗，这个cuda版本我是直接覆盖了之前的版本，可能变不回去了。还有就是我最近比较忙，可能没有时间打理这个项目，如果你是要用在其它项目或者比赛上，建议用我上面给的链接，如果是自己学习的话可以自己单步调试找一下bug，对自己的代码能力和网络的理解都是有帮助的。这个网络其实就是参照drbox改的，和原来的yolo差别不大，就是多回归了一个角度以及anchor不一样，很简单
 
&mdash;

**Comment by clw5180** [comment]
有正在研究这个项目的朋友可以加我的企鹅，623497281
