### ISSUE TITLE
labelImg打不开图片

### ISSUE THREAD

**Issue by veraluoshu** [woshiwwwppp/ryolov3research-pytorch-master#7]
图片时jpg格式的，用这个标注工具打不开，如何操作可以实现标注呢？

**Comment by MiXaiLL76** [comment]
use https://github.com/cgvict/roLabelImg

**Comment by veraluoshu** [comment]
请问您试过这个标注工具吗？在安装的时候遇到这个问题，请问您有遇到吗？

![image](https://user-images.githubusercontent.com/54836878/77631045-01d18d80-6f87-11ea-9d7e-bd4ac7586d65.png)

**Comment by MiXaiLL76** [comment]
> 
> 
> 请问您试过这个标注工具吗？在安装的时候遇到这个问题，请问您有遇到吗？
> 
I think you just need to

```
pip install codecs
```

**Comment by veraluoshu** [comment]
我试过以后还是不行，包括更新了pip和网上查的更换镜像网站，但还是出现了这个错误，请问您有什么解决办法吗
![image](https://user-images.githubusercontent.com/54836878/77813941-9226e400-70e7-11ea-881a-9f4cc4c575d2.png)

**Comment by MiXaiLL76** [comment]
> 
> 
> 我试过以后还是不行，包括更新了pip和网上查的更换镜像网站，但还是出现了这个错误，请问您有什么解决办法吗


Reinstall python because it is a standard library!

/usr/lib/python2.7/codecs.py
/usr/lib/python3.7/codecs.py

**Comment by veraluoshu** [comment]
请问如果用cgvict的roLabelImg进行标注，generate_data.py角度转弧度那里是不是就不用考虑了？
![image](https://user-images.githubusercontent.com/54836878/79032116-7be45200-7bd6-11ea-8436-40f3b522be9f.png)
